### ISSUE TITLE
Cross-modality

### ISSUE THREAD

**Issue by che1007** [lik1996/iCMFormer#2]
![image](https://github.com/lik1996/iCMFormer/assets/67545227/4ec1cbb2-a379-4c5e-b1eb-c34fb64cfe1d)
I have some questions about this table. What does the guidance from Y to X, or X to Y, mean in this table?

**Comment by che1007** [comment]
![image](https://github.com/lik1996/iCMFormer/assets/67545227/f2720e71-5f41-4a5e-83f7-00a0827752c9)
I still have a question about the data path. I believe that image features and click features are fed into the cross-modality block to perform cross-attention. Therefore, the output of the cross-modality block should be a single feature. Why, then, are there two outputs from the cross-modality block?

**Comment by lik1996** [comment]
> ![image](https://private-user-images.githubusercontent.com/67545227/284041087-4ec1cbb2-a379-4c5e-b1eb-c34fb64cfe1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODM2NDAsIm5iZiI6MTcwMjg4MzM0MCwicGF0aCI6Ii82NzU0NTIyNy8yODQwNDEwODctNGVjMWNiYjItYTM3OS00YzVlLWIxZWItYzM0ZmI2NGNmZTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA3MDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NWIzZThhOWZmOWUyOGQwOWY5ZWJjNzc5ZjJkNWM4NGNlMWY4NzJhMjRlZGRmNjAyNGJjYjU3MDQyODQzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i4faBE9VpOh3I7kQlCHmvNiW-QBVm2yy24dIHSQk0Ao) I have some questions about this table. What does the guidance from Y to X, or X to Y, mean in this table?

Hi,

The guidance means the cross-attention part, in short, the query from one modality to the keys from the other modality.

**Comment by lik1996** [comment]
> ![image](https://private-user-images.githubusercontent.com/67545227/284046114-f2720e71-5f41-4a5e-83f7-00a0827752c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODM2NDAsIm5iZiI6MTcwMjg4MzM0MCwicGF0aCI6Ii82NzU0NTIyNy8yODQwNDYxMTQtZjI3MjBlNzEtNWY0MS00YTVlLTgzZjctMDBhMDgyNzc1MmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA3MDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4N2M4MzI3OThiMzBjMWY4ZDdkYTA2OTljM2EzMzgxMWEzZDZlZDRkYWY5MzhlNDAyZGMyZmUyNzlhODczNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TDjeQMfVYTbGrMQgN8qZrd_7Li5mg57RbZGVTjdKCGQ) I still have a question about the data path. I believe that image features and click features are fed into the cross-modality block to perform cross-attention. Therefore, the output of the cross-modality block should be a single feature. Why, then, are there two outputs from the cross-modality block?

Yes, the illustration represents the dual paths for the image features and click features. If we only consider one direction guidance, then we take the features before it fed into the cross-modality blocks.
